services:

    rpg.creature_factory:
      class: RPGBundle\Service\CreatureFactoryService

    rpg.attack_strategy:
      class: RPGBundle\Service\SimpleAttackStrategyService

    rpg.action:
      class: RPGBundle\Service\ActionService
      autowire: true

    rpg.action_factory:
      class: RPGBundle\Service\ActionFactoryService

    rpg.fight:
      class: RPGBundle\Service\FightService
      autowire: true

    rpg.profile:
      class: RPGBundle\Service\ProfileService
      arguments: ['@doctrine.orm.default_entity_manager', '@validator']

    character_command:
      class: RPGBundle\Command\CharacterCommand
      tags:
        - {name: console.command}

    game_command:
      class: RPGBundle\Command\GameCommand
      tags:
        - {name: console.command}
