services:

    rpg.example.sum:
      class: RPGBundle\Service\SumService

    rpg.creature_factory:
      class: RPGBundle\Service\CreatureFactoryService

    rpg.attack_strategy:
      class: RPGBundle\Service\SimpleAttackStrategyService

    rpg.action:
      class: RPGBundle\Service\ActionService
      autowire: true

    rpg.action_factory:
      class: RPGBundle\Service\ActionFactoryService

    rpg.game:
      class: RPGBundle\Service\GameService
      autowire: true

    rpg.profile:
      class: RPGBundle\Service\ProfileService
      arguments: ['@doctrine.orm.default_entity_manager', '@validator']

    default_controller:
      class: RPGBundle\Controller\DefaultController
      autowire: true

    test_command:
      class: RPGBundle\Command\TestCommand
      tags:
        - {name: console.command}

    character_command:
      class: RPGBundle\Command\CharacterCommand
      tags:
        - {name: console.command}

    game_command:
      class: RPGBundle\Command\GameCommand
      tags:
        - {name: console.command}
